[project]
name = "mitocancer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "psycopg2>=2.9.12",
    "pydeseq2>=0.5.4",
    "requests>=2.34.2",
    "rpy2>=3.6.7",
    "sqlalchemy>=2.0.50",
    "xenapython",
    "xlrd>=2.0.2",
]

[tool.uv.sources]
xenapython = { git = "https://github.com/ucscXena/xenaPython" }
